/**
 * Mirrors workers/runtime/catalog/emotes.json (id + display name only —
 * the dashboard just needs to render a picker, not resolve chat triggers).
 * Keep in sync by hand; see docs/decisions.md, 2026-07-20 "emote catalog
 * replaced with the real current list" for where these came from.
 */
export const EMOTE_CATALOG: { id: string; name: string }[] = [
  { id: "dance-aerobics", name: "Push Ups" },
  { id: "dance-anime", name: "Anime Dance" },
  { id: "dance-blackpink", name: "K-Pop Dance" },
  { id: "dance-breakdance", name: "Breakdance" },
  { id: "dance-creepypuppet", name: "Creepy Puppet" },
  { id: "dance-duckwalk", name: "Duck Walk" },
  { id: "dance-employee", name: "Push It" },
  { id: "dance-floss", name: "Floss" },
  { id: "dance-freshprince", name: "The Fresh Step" },
  { id: "dance-griddy", name: "Gwiddy" },
  { id: "dance-handsup", name: "Hands in the Air" },
  { id: "dance-icecream", name: "Ice Cream Dance" },
  { id: "dance-jinglebell", name: "Jinglebell" },
  { id: "dance-kawai", name: "Kawaii" },
  { id: "dance-macarena", name: "Macarena" },
  { id: "dance-martial-artist", name: "Karate" },
  { id: "dance-metal", name: "Rock Out" },
  { id: "dance-mine", name: "Mine Dance" },
  { id: "dance-orangejustice", name: "Orange Juice Dance" },
  { id: "dance-pennywise", name: "Penny's Dance" },
  { id: "dance-pinguin", name: "Penguin Dance" },
  { id: "dance-popularvibe", name: "Popular Vibe" },
  { id: "dance-robotic", name: "Robotic" },
  { id: "dance-russian", name: "Russian Dance" },
  { id: "dance-sexy", name: "Sexy Dance" },
  { id: "dance-shoppingcart", name: "Let's Go Shopping" },
  { id: "dance-singleladies", name: "Ring on It" },
  { id: "dance-smoothwalk", name: "Smoothwalk" },
  { id: "dance-spiritual", name: "Yoga Flow" },
  { id: "dance-swagbounce", name: "Swag Bounce" },
  { id: "dance-tiktok10", name: "TikTok Dance 10" },
  { id: "dance-tiktok2", name: "Don't Start Now" },
  { id: "dance-tiktok8", name: "Savage Dance" },
  { id: "dance-tiktok9", name: "TikTok Dance 9" },
  { id: "dance-touch", name: "Touch" },
  { id: "dance-true-heart", name: "Pure Heart" },
  { id: "dance-twerk", name: "Twerk It Out" },
  { id: "dance-voguehands", name: "Vogue Hands" },
  { id: "dance-weird", name: "Weird Dance" },
  { id: "dance-woah", name: "The Woah" },
  { id: "dance-wrong", name: "Wrong Dance" },
  { id: "dance-zombie", name: "Dance Zombie" },
  { id: "emoji-angry", name: "Angry" },
  { id: "emoji-arrogance", name: "Arrogance" },
  { id: "emoji-celebrate", name: "Raise The Roof" },
  { id: "emoji-clapping", name: "Clap" },
  { id: "emoji-crying", name: "Sob" },
  { id: "emoji-cursing", name: "Cursing Emote" },
  { id: "emoji-dizzy", name: "Stunned" },
  { id: "emoji-eyeroll", name: "Eyeroll" },
  { id: "emoji-flex", name: "Flex" },
  { id: "emoji-gagging", name: "Tummy Ache" },
  { id: "emoji-ghost", name: "Ghost" },
  { id: "emoji-give-up", name: "Give Up" },
  { id: "emoji-hadoken", name: "Fireball Lunge" },
  { id: "emoji-halo", name: "Levitate" },
  { id: "emoji-lying", name: "Lying" },
  { id: "emoji-mind-blown", name: "Mind Blown" },
  { id: "emoji-naughty", name: "Naughty" },
  { id: "emoji-poop", name: "Stinky" },
  { id: "emoji-pray", name: "Pray" },
  { id: "emoji-punch", name: "Punch" },
  { id: "emoji-scared", name: "Gasp" },
  { id: "emoji-sick", name: "Sick" },
  { id: "emoji-smirking", name: "Smirk" },
  { id: "emoji-sneeze", name: "Sneeze" },
  { id: "emoji-there", name: "Point" },
  { id: "emoji-thumbsup", name: "Thumbs Up" },
  { id: "emote-afk-idle", name: "AFK" },
  { id: "emote-apart", name: "Falling Apart" },
  { id: "emote-astronaut", name: "Astronaut" },
  { id: "emote-attention", name: "Attention" },
  { id: "emote-baseball", name: "Home Run!" },
  { id: "emote-boo", name: "Boo" },
  { id: "emote-bow", name: "Bow" },
  { id: "emote-boxer", name: "Boxer" },
  { id: "emote-bunnyhop", name: "Bunny Hop" },
  { id: "emote-celebrationstep", name: "Celebration Step" },
  { id: "emote-charging", name: "Charging" },
  { id: "emote-cold", name: "Cold" },
  { id: "emote-collab-photo-right", name: "Highrise Star" },
  { id: "emote-confused", name: "Confusion" },
  { id: "emote-creepycute", name: "Creepycute" },
  { id: "emote-curtsy", name: "Curtsy" },
  { id: "emote-cute", name: "Cute" },
  { id: "emote-cutey", name: "Cutey" },
  { id: "emote-dab", name: "Dab" },
  { id: "emote-death", name: "Revival" },
  { id: "emote-death2", name: "Collapse" },
  { id: "emote-deathdrop", name: "Faint Drop" },
  { id: "emote-disappear", name: "Blast Off" },
  { id: "emote-disco", name: "Disco" },
  { id: "emote-elbowbump", name: "Elbow Bump" },
  { id: "emote-embarrassed", name: "Embarrassed" },
  { id: "emote-energyball", name: "Energy Ball" },
  { id: "emote-exasperated", name: "Exasperated" },
  { id: "emote-exasperatedb", name: "Face Palm" },
  { id: "emote-fail1", name: "Fall" },
  { id: "emote-fail2", name: "Clumsy" },
  { id: "emote-fainting", name: "Faint" },
  { id: "emote-fashionista", name: "Fashionista" },
  { id: "emote-float", name: "Float" },
  { id: "emote-frog", name: "Frog" },
  { id: "emote-frollicking", name: "Frolic" },
  { id: "emote-frustrated", name: "Frustrated" },
  { id: "emote-gangnam", name: "Gangnam Style" },
  { id: "emote-ghost-idle", name: "Ghost Float" },
  { id: "emote-gift", name: "This Is For You" },
  { id: "emote-gordonshuffle", name: "Moonwalk" },
  { id: "emote-graceful", name: "Graceful" },
  { id: "emote-gravity", name: "Gravity" },
  { id: "emote-greedy", name: "Greedy Emote" },
  { id: "emote-handstand", name: "Handstand" },
  { id: "emote-happy", name: "Happy" },
  { id: "emote-harlemshake", name: "Harlem Shake" },
  { id: "emote-headball", name: "Headball" },
  { id: "emote-headblowup", name: "Head Blowup" },
  { id: "emote-hearteyes", name: "Heart Eyes" },
  { id: "emote-heartfingers", name: "Heart Fingers" },
  { id: "emote-heartshape", name: "Heart Shape" },
  { id: "emote-hello", name: "Hello" },
  { id: "emote-hero", name: "Hero Entrance" },
  { id: "emote-hot", name: "Sweating" },
  { id: "emote-hug", name: "Hug" },
  { id: "emote-hugyourself", name: "Hug Yourself" },
  { id: "emote-hyped", name: "Hyped" },
  { id: "emote-iceskating", name: "Ice Skating" },
  { id: "emote-jetpack", name: "Imaginary Jetpack" },
  { id: "emote-judochop", name: "Judo Chop" },
  { id: "emote-jumpb", name: "Jump" },
  { id: "emote-kawaiigogo", name: "KawaiiGoGo" },
  { id: "emote-kicking", name: "Super Kick" },
  { id: "emote-kiss", name: "Kiss" },
  { id: "emote-lagughing", name: "Laugh (Alt)" },
  { id: "emote-laughing", name: "Laugh" },
  { id: "emote-laughing2", name: "Amused" },
  { id: "emote-levelup", name: "Level Up!" },
  { id: "emote-lust", name: "Flirty Wave" },
  { id: "emote-maniac", name: "Maniac" },
  { id: "emote-meditate-idle", name: "Zen Mode" },
  { id: "emote-model", name: "Model" },
  { id: "emote-monster_fail", name: "Monster Fail" },
  { id: "emote-nightfever", name: "Night Fever" },
  { id: "emote-ninjarun", name: "Ninja Run" },
  { id: "emote-no", name: "No" },
  { id: "emote-panic", name: "Panic" },
  { id: "emote-peace", name: "Peace" },
  { id: "emote-peekaboo", name: "Peekaboo!" },
  { id: "emote-pose1", name: "Pose 1" },
  { id: "emote-pose10", name: "Pose 10" },
  { id: "emote-pose3", name: "Pose 3" },
  { id: "emote-pose5", name: "Pose 5" },
  { id: "emote-pose6", name: "SurpriseBig" },
  { id: "emote-pose7", name: "Pose 7" },
  { id: "emote-pose8", name: "Pose 8" },
  { id: "emote-pose9", name: "Ditzy Pose" },
  { id: "emote-proposing", name: "Proposing" },
  { id: "emote-punkguitar", name: "Punk Guitar" },
  { id: "emote-puppet", name: "Puppet" },
  { id: "emote-rainbow", name: "Rainbow" },
  { id: "emote-repose", name: "Repose" },
  { id: "emote-robot", name: "Robot" },
  { id: "emote-rofl", name: "ROFL!" },
  { id: "emote-roll", name: "Roll" },
  { id: "emote-ropepull", name: "Rope Pull" },
  { id: "emote-sad", name: "Sad" },
  { id: "emote-secrethandshake", name: "Secret Handshake" },
  { id: "emote-shrink", name: "Shrink" },
  { id: "emote-shy", name: "Shy" },
  { id: "emote-shy2", name: "Advanced Shy" },
  { id: "emote-slap", name: "Slap" },
  { id: "emote-sleigh", name: "Sleigh" },
  { id: "emote-snake", name: "Snake" },
  { id: "emote-snowangel", name: "Snow Angel" },
  { id: "emote-snowball", name: "Snowball Fight!" },
  { id: "emote-spiderman", name: "Hanging Around" },
  { id: "emote-splitsdrop", name: "Splits Drop" },
  { id: "emote-stargaze", name: "Star Gazing" },
  { id: "emote-suckthumb", name: "Thumb Suck" },
  { id: "emote-sumo", name: "Sumo Fight" },
  { id: "emote-superpose", name: "Superpose" },
  { id: "emote-superpunch", name: "Super Punch" },
  { id: "emote-superrun", name: "Super Run" },
  { id: "emote-swordfight", name: "Swordfight" },
  { id: "emote-tapdance", name: "Tap Dance" },
  { id: "emote-telekinesis", name: "Telekinesis" },
  { id: "emote-teleporting", name: "Teleporting" },
  { id: "emote-theatrical", name: "Theatrical" },
  { id: "emote-think", name: "Think" },
  { id: "emote-timejump", name: "TimeJump" },
  { id: "emote-tired", name: "Tired" },
  { id: "emote-wave", name: "The Wave" },
  { id: "emote-wings", name: "I Believe I Can Fly" },
  { id: "emote-yes", name: "Yes" },
  { id: "emote-zombierun", name: "Zombie Run" },
  { id: "idle-angry", name: "Irritated" },
  { id: "idle-dance-casual", name: "Casual Dance" },
  { id: "idle-dance-headbobbing", name: "Feel The Beat" },
  { id: "idle-dance-swinging", name: "Boogie Swing" },
  { id: "idle-dance-tiktok4", name: "TikTok Dance 4" },
  { id: "idle-dance-tiktok7", name: "Tiktok 7" },
  { id: "idle-enthusiastic", name: "Enthused" },
  { id: "idle-fighter", name: "Fighter Idle" },
  { id: "idle-floorsleeping", name: "Cozy Nap" },
  { id: "idle-floorsleeping2", name: "Relaxing" },
  { id: "idle-guitar", name: "Air Guitar" },
  { id: "idle-hero", name: "Hero Pose" },
  { id: "idle-lookup", name: "Ponder" },
  { id: "idle-loop-aerobics", name: "Aerobics" },
  { id: "idle-loop-annoyed", name: "Annoyed" },
  { id: "idle-loop-happy", name: "Chillin'" },
  { id: "idle-loop-sad", name: "Bummed" },
  { id: "idle-loop-shy", name: "Shy (Loop)" },
  { id: "idle-loop-sitfloor", name: "Sit" },
  { id: "idle-loop-tapdance", name: "Tap Loop" },
  { id: "idle-loop-tired", name: "Sleepy (Loop)" },
  { id: "idle-nervous", name: "Nervous" },
  { id: "idle-posh", name: "Posh" },
  { id: "idle-sad", name: "Pouty Face" },
  { id: "idle-sleep", name: "Sleepy" },
  { id: "idle-space", name: "Zero Gravity Chill" },
  { id: "idle-toilet", name: "Toilet" },
  { id: "idle-uwu", name: "UwU" },
  { id: "idle-wild", name: "Scritchy" },
  { id: "idle_layingdown", name: "Attentive" },
  { id: "idle_layingdown2", name: "Relaxed (Lying Down)" },
  { id: "idle_singing", name: "Singing" },
  { id: "idle_zombie", name: "Zombie" },
  { id: "sit-idle-cute", name: "Rest" },
  { id: "sit-idle-laidBack", name: "Kicking Back" },
  { id: "sit-open", name: "Laid Back" },
  { id: "sit-relaxed", name: "Relaxed (Sitting)" },
];
